export const PERMISSIONS = [
  "dashboard.view",
  "analytics.view",
  "computers.view",
  "computers.edit",
  "computers.control",
  "computers.stream",
  "computers.profiles",
  "players.view",
  "players.edit",
  "players.topup",
  "products.view",
  "products.edit",
  "packages.view",
  "packages.edit",
  "pos.use",
  "shifts.view",
  "shifts.manage",
  "settings.bonus",
  "settings.tariffs",
  "reservations.view",
  "reservations.edit",
  "admins.view",
  "admins.edit",
  "reports.export",
  "audit.view",
  "announcements.send",
  "hardware.view",
  "telegram.manage",
  "anticheat.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
export const ALL_PERMISSIONS: Permission[] = [...PERMISSIONS];
